"""add face_embeddings and face_images

Revision ID: be4c008c9294
Revises: 2143901ce032
Create Date: 2026-06-14 01:03:53.279116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4c008c9294'
down_revision: Union[str, None] = '2143901ce032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embeddings', sa.LargeBinary(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_embeddings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_embeddings_user_id'), ['user_id'], unique=True)

    op.create_table('face_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_images_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_images_user_id'))
        batch_op.drop_index(batch_op.f('ix_face_images_id'))

    op.drop_table('face_images')
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embeddings_user_id'))
        batch_op.drop_index(batch_op.f('ix_face_embeddings_id'))

    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
